### ISSUE TITLE
Advice

### ISSUE THREAD

**Issue by OxideDevX** [Josh-J340/Matrix-rain#1]
Hello. To make it funnier, you can rewrite your script a little differently.
Code:
@echo off
color 0a
mode 1000
:a
echo %random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%
goto a

**Comment by Josh-J340** [comment]
> Hello. To make it funnier, you can rewrite your script a little differently.
> Code:
> @echo off
> color 0a
> mode 1000
> :a
> echo %random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%
> goto a

sure! ill check it out rn ;)

**Comment by Josh-J340** [comment]
> Hello. To make it funnier, you can rewrite your script a little differently.
> Code:
> @echo off
> color 0a
> mode 1000
> :a
> echo %random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%%random%
> goto a

looking at the code, i dont really see a change, i just see a change in numbers
